name: 'Upload to Release Action'
description: 'A GitHub Action that uploads a file to a new release.'
author: 'johnjjung'
inputs:
  name:
    description: 'Repo username/repo-name'
    required: true
  path:
    description: 'Path to the flat directory'
    required: true
  content-type:
    description: 'Content type for the file'
    required: false
    default: 'application/octet-stream'
  repo-token:
    description: 'secrets.GITHUB_TOKEN'
    required: true
  release_id:
    description: 'Release Version ID'
    required: true
  release_name:
    description: 'Release Name, or use GITHUB_SHA'
  release-repo:
    description: 'username/repo-name'
  action:
    description: 'enum of published, unpublished, etc..'
runs:
  using: 'node12'
  main: 'lib/main.js'
