name: 'Upload to Release Action'
description: 'A GitHub Action that uploads a file to a new release.'
author: 'johnjjung'
inputs:
  name:
    description: 'Artifact name'
    required: true
  path:
    description: 'Path to the file to upload'
    required: true
  content-type:
    description: 'Content type for the file'
    required: false
    default: 'application/octet-stream'
  repo-token:
    description: 'secrets.GITHUB_TOKEN'
    required: true
  release_id:
    description: 'Release Version ID'
    required: true
  release-repo:
    description: 'username/repo-name'
  release_name:
    description: 'Release Name'
    required: false
    default: 'Draft Release'
  action:
    description: 'enum of published, unpublished, etc..'
runs:
  using: 'node12'
  main: 'lib/main.js'
