name: "Release"
on: [release]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: Shopify/upload-to-release@master
      with:
        name: LICENSE
        path: LICENSE
        content-type: text/plain
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release_id: x.x.x
        release-repo: lucyio/upload-to-release
        action: unpublished
